dist: trusty
language: java
jdk: oraclejdk8

addons:
  apt:
    packages:
      - dpkg # this is required for fixing Travis' invalid chrome version issue
  chrome: stable

services:
  - docker

before_install:
  - chromeVersion=$(google-chrome --version | grep -oiE " [0-9]{1,3}." | grep -oiE "[0-9]*")
  - latestChromeDriverURL=$(wget http://chromedriver.storage.googleapis.com/LATEST_RELEASE_${chromeVersion} -q -O -)
  - wget "http://chromedriver.storage.googleapis.com/${latestChromeDriverURL}/chromedriver_linux64.zip"
  - unzip chromedriver_linux64.zip -d /home/travis/bin
  - chmod +x /home/travis/bin/chromedriver

jobs:
  include:
    - name: Load test 1
      language: node_js
      node_js: 14
      before_install: skip
      script:
        - export APPLITOOLS_API_KEY=Y23EJfdvNrMBsvW97yYYviHz7Z69scgghK8aa77aHP94110
        - npm install --save-dev @applitools/eyes-storybook
        - touch applitools.config.js
        - sed 's+{buildName}+LoadTest1+g' config.file.template > applitools.config.js
        - npx eyes-storybook --conf applitools.config.js
    - name: Load test 2
      language: node_js
      node_js: 14
      before_install: skip
      script:
        -  export APPLITOOLS_API_KEY=Jie0hycCfMPWfSQj5iXhYN4xUo9NQ8llJPX0eiqWrvI110
        - npm install --save-dev @applitools/eyes-storybook
        - touch applitools.config.js
        - sed 's+{buildName}+LoadTest1+g' config.file.template > applitools.config.js
        - npx eyes-storybook --conf applitools.config.js
