dist: trusty
language: java
jdk: oraclejdk8

addons:
  apt:
    packages:
      - dpkg # this is required for fixing Travis' invalid chrome version issue
  chrome: stable

services:
  - docker

before_install:
  - chromeVersion=$(google-chrome --version | grep -oiE " [0-9]{1,3}." | grep -oiE "[0-9]*")
  - latestChromeDriverURL=$(wget http://chromedriver.storage.googleapis.com/LATEST_RELEASE_${chromeVersion} -q -O -)
  - wget "http://chromedriver.storage.googleapis.com/${latestChromeDriverURL}/chromedriver_linux64.zip"
  - unzip chromedriver_linux64.zip -d /home/travis/bin
  - chmod +x /home/travis/bin/chromedriver

jobs:
  include:
    - name: Load test 1
      language: node_js
      node_js: 14
      before_install: skip
      script:
        - export APPLITOOLS_API_KEY=Y23EJfdvNrMBsvW97yYYviHz7Z69scgghK8aa77aHP94110
        - npm install --save-dev @applitools/eyes-storybook
        - touch applitools.config.js
        - sed 's+{buildName}+LoadTest1+g' config.file.template > applitools.config.js
        - npx eyes-storybook --conf applitools.config.js
    - name: Load test 2
      language: node_js
      node_js: 14
      before_install: skip
      script:
        -  export APPLITOOLS_API_KEY=Jie0hycCfMPWfSQj5iXhYN4xUo9NQ8llJPX0eiqWrvI110
        - npm install --save-dev @applitools/eyes-storybook
        - touch applitools.config.js
        - sed 's+{buildName}+LoadTest2+g' config.file.template > applitools.config.js
        - npx eyes-storybook --conf applitools.config.js
    - name: Load test 3
      language: node_js
      node_js: 14
      before_install: skip
      script:
        - export APPLITOOLS_API_KEY=Y23EJfdvNrMBsvW97yYYviHz7Z69scgghK8aa77aHP94110
        - npm install --save-dev @applitools/eyes-storybook
        - touch applitools.config.js
        - sed 's+{buildName}+LoadTest3+g' config.file.template > applitools.config.js
        - npx eyes-storybook --conf applitools.config.js
    - name: Load test 4
      language: node_js
      node_js: 14
      before_install: skip
      script:
        -  export APPLITOOLS_API_KEY=Jie0hycCfMPWfSQj5iXhYN4xUo9NQ8llJPX0eiqWrvI110
        - npm install --save-dev @applitools/eyes-storybook
        - touch applitools.config.js
        - sed 's+{buildName}+LoadTest4+g' config.file.template > applitools.config.js
        - npx eyes-storybook --conf applitools.config.js
    - name: Load test 5
      language: node_js
      node_js: 14
      before_install: skip
      script:
        - export APPLITOOLS_API_KEY=Y23EJfdvNrMBsvW97yYYviHz7Z69scgghK8aa77aHP94110
        - npm install --save-dev @applitools/eyes-storybook
        - touch applitools.config.js
        - sed 's+{buildName}+LoadTest5+g' config.file.template > applitools.config.js
        - npx eyes-storybook --conf applitools.config.js
    - name: Load test 6
      language: node_js
      node_js: 14
      before_install: skip
      script:
        -  export APPLITOOLS_API_KEY=Jie0hycCfMPWfSQj5iXhYN4xUo9NQ8llJPX0eiqWrvI110
        - npm install --save-dev @applitools/eyes-storybook
        - touch applitools.config.js
        - sed 's+{buildName}+LoadTest6+g' config.file.template > applitools.config.js
        - npx eyes-storybook --conf applitools.config.js
    - name: Load test 7
      language: node_js
      node_js: 14
      before_install: skip
      script:
        - export APPLITOOLS_API_KEY=Y23EJfdvNrMBsvW97yYYviHz7Z69scgghK8aa77aHP94110
        - npm install --save-dev @applitools/eyes-storybook
        - touch applitools.config.js
        - sed 's+{buildName}+LoadTest7+g' config.file.template > applitools.config.js
        - npx eyes-storybook --conf applitools.config.js
    - name: Load test 8
      language: node_js
      node_js: 14
      before_install: skip
      script:
        -  export APPLITOOLS_API_KEY=Jie0hycCfMPWfSQj5iXhYN4xUo9NQ8llJPX0eiqWrvI110
        - npm install --save-dev @applitools/eyes-storybook
        - touch applitools.config.js
        - sed 's+{buildName}+LoadTest8+g' config.file.template > applitools.config.js
        - npx eyes-storybook --conf applitools.config.js
    - name: Load test 9
      language: node_js
      node_js: 14
      before_install: skip
      script:
        - export APPLITOOLS_API_KEY=Y23EJfdvNrMBsvW97yYYviHz7Z69scgghK8aa77aHP94110
        - npm install --save-dev @applitools/eyes-storybook
        - touch applitools.config.js
        - sed 's+{buildName}+LoadTest9+g' config.file.template > applitools.config.js
        - npx eyes-storybook --conf applitools.config.js
    - name: Load test 10
      language: node_js
      node_js: 14
      before_install: skip
      script:
        -  export APPLITOOLS_API_KEY=Jie0hycCfMPWfSQj5iXhYN4xUo9NQ8llJPX0eiqWrvI110
        - npm install --save-dev @applitools/eyes-storybook
        - touch applitools.config.js
        - sed 's+{buildName}+LoadTest10+g' config.file.template > applitools.config.js
        - npx eyes-storybook --conf applitools.config.js
    - name: Load test 11
      language: node_js
      node_js: 14
      before_install: skip
      script:
        - export APPLITOOLS_API_KEY=Y23EJfdvNrMBsvW97yYYviHz7Z69scgghK8aa77aHP94110
        - npm install --save-dev @applitools/eyes-storybook
        - touch applitools.config.js
        - sed 's+{buildName}+LoadTest11+g' config.file.template > applitools.config.js
        - npx eyes-storybook --conf applitools.config.js
    - name: Load test 12
      language: node_js
      node_js: 14
      before_install: skip
      script:
        -  export APPLITOOLS_API_KEY=Jie0hycCfMPWfSQj5iXhYN4xUo9NQ8llJPX0eiqWrvI110
        - npm install --save-dev @applitools/eyes-storybook
        - touch applitools.config.js
        - sed 's+{buildName}+LoadTest12+g' config.file.template > applitools.config.js
        - npx eyes-storybook --conf applitools.config.js
    - name: Load test 13
      language: node_js
      node_js: 14
      before_install: skip
      script:
        - export APPLITOOLS_API_KEY=Y23EJfdvNrMBsvW97yYYviHz7Z69scgghK8aa77aHP94110
        - npm install --save-dev @applitools/eyes-storybook
        - touch applitools.config.js
        - sed 's+{buildName}+LoadTest13+g' config.file.template > applitools.config.js
        - npx eyes-storybook --conf applitools.config.js
    - name: Load test 14
      language: node_js
      node_js: 14
      before_install: skip
      script:
        -  export APPLITOOLS_API_KEY=Jie0hycCfMPWfSQj5iXhYN4xUo9NQ8llJPX0eiqWrvI110
        - npm install --save-dev @applitools/eyes-storybook
        - touch applitools.config.js
        - sed 's+{buildName}+LoadTest14+g' config.file.template > applitools.config.js
        - npx eyes-storybook --conf applitools.config.js
    - name: Load test 15
      language: node_js
      node_js: 14
      before_install: skip
      script:
        - export APPLITOOLS_API_KEY=Y23EJfdvNrMBsvW97yYYviHz7Z69scgghK8aa77aHP94110
        - npm install --save-dev @applitools/eyes-storybook
        - touch applitools.config.js
        - sed 's+{buildName}+LoadTest15+g' config.file.template > applitools.config.js
        - npx eyes-storybook --conf applitools.config.js
    - name: Load test 16
      language: node_js
      node_js: 14
      before_install: skip
      script:
        -  export APPLITOOLS_API_KEY=Jie0hycCfMPWfSQj5iXhYN4xUo9NQ8llJPX0eiqWrvI110
        - npm install --save-dev @applitools/eyes-storybook
        - touch applitools.config.js
        - sed 's+{buildName}+LoadTest16+g' config.file.template > applitools.config.js
        - npx eyes-storybook --conf applitools.config.js
    - name: Load test 17
      language: node_js
      node_js: 14
      before_install: skip
      script:
        - export APPLITOOLS_API_KEY=Y23EJfdvNrMBsvW97yYYviHz7Z69scgghK8aa77aHP94110
        - npm install --save-dev @applitools/eyes-storybook
        - touch applitools.config.js
        - sed 's+{buildName}+LoadTest17+g' config.file.template > applitools.config.js
        - npx eyes-storybook --conf applitools.config.js
    - name: Load test 18
      language: node_js
      node_js: 14
      before_install: skip
      script:
        -  export APPLITOOLS_API_KEY=Jie0hycCfMPWfSQj5iXhYN4xUo9NQ8llJPX0eiqWrvI110
        - npm install --save-dev @applitools/eyes-storybook
        - touch applitools.config.js
        - sed 's+{buildName}+LoadTest18+g' config.file.template > applitools.config.js
        - npx eyes-storybook --conf applitools.config.js
    - name: Load test 19
      language: node_js
      node_js: 14
      before_install: skip
      script:
        - export APPLITOOLS_API_KEY=Y23EJfdvNrMBsvW97yYYviHz7Z69scgghK8aa77aHP94110
        - npm install --save-dev @applitools/eyes-storybook
        - touch applitools.config.js
        - sed 's+{buildName}+LoadTest19+g' config.file.template > applitools.config.js
        - npx eyes-storybook --conf applitools.config.js
    - name: Load test 20
      language: node_js
      node_js: 14
      before_install: skip
      script:
        -  export APPLITOOLS_API_KEY=Jie0hycCfMPWfSQj5iXhYN4xUo9NQ8llJPX0eiqWrvI110
        - npm install --save-dev @applitools/eyes-storybook
        - touch applitools.config.js
        - sed 's+{buildName}+LoadTest20+g' config.file.template > applitools.config.js
        - npx eyes-storybook --conf applitools.config.js
    - name: Load test 21
      language: node_js
      node_js: 14
      before_install: skip
      script:
        - export APPLITOOLS_API_KEY=Y23EJfdvNrMBsvW97yYYviHz7Z69scgghK8aa77aHP94110
        - npm install --save-dev @applitools/eyes-storybook
        - touch applitools.config.js
        - sed 's+{buildName}+LoadTest21+g' config.file.template > applitools.config.js
        - npx eyes-storybook --conf applitools.config.js
    - name: Load test 22
      language: node_js
      node_js: 14
      before_install: skip
      script:
        -  export APPLITOOLS_API_KEY=Jie0hycCfMPWfSQj5iXhYN4xUo9NQ8llJPX0eiqWrvI110
        - npm install --save-dev @applitools/eyes-storybook
        - touch applitools.config.js
        - sed 's+{buildName}+LoadTest22+g' config.file.template > applitools.config.js
        - npx eyes-storybook --conf applitools.config.js
    - name: Load test 23
      language: node_js
      node_js: 14
      before_install: skip
      script:
        - export APPLITOOLS_API_KEY=Y23EJfdvNrMBsvW97yYYviHz7Z69scgghK8aa77aHP94110
        - npm install --save-dev @applitools/eyes-storybook
        - touch applitools.config.js
        - sed 's+{buildName}+LoadTest23+g' config.file.template > applitools.config.js
        - npx eyes-storybook --conf applitools.config.js
    - name: Load test 24
      language: node_js
      node_js: 14
      before_install: skip
      script:
        -  export APPLITOOLS_API_KEY=Jie0hycCfMPWfSQj5iXhYN4xUo9NQ8llJPX0eiqWrvI110
        - npm install --save-dev @applitools/eyes-storybook
        - touch applitools.config.js
        - sed 's+{buildName}+LoadTest24+g' config.file.template > applitools.config.js
        - npx eyes-storybook --conf applitools.config.js
